# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 603)
        font = QtGui.QFont()
        font.setFamily("Montserrat Thin")
        font.setPointSize(40)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(78, 63, 96);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.playlistView = QtWidgets.QListView(self.centralwidget)
        self.playlistView.setGeometry(QtCore.QRect(20, 70, 737, 442))
        self.playlistView.setAcceptDrops(True)
        self.playlistView.setStyleSheet("background-color: rgb(57, 46, 69);\n"
"border:none;\n"
"border-radius:25px ;")
        self.playlistView.setProperty("showDropIndicator", True)
        self.playlistView.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.playlistView.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.playlistView.setAlternatingRowColors(True)
        self.playlistView.setUniformItemSizes(True)
        self.playlistView.setObjectName("playlistView")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 530, 731, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.currentTimeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.currentTimeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.currentTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentTimeLabel.setObjectName("currentTimeLabel")
        self.horizontalLayout_5.addWidget(self.currentTimeLabel)
        self.timeSlider_2 = QtWidgets.QSlider(self.layoutWidget)
        self.timeSlider_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.timeSlider_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeSlider_2.setStyleSheet("background-color: rgb(78, 63, 96);\n"
"color: rgb(181, 144, 204);")
        self.timeSlider_2.setPageStep(0)
        self.timeSlider_2.setSliderPosition(0)
        self.timeSlider_2.setTracking(True)
        self.timeSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider_2.setInvertedAppearance(False)
        self.timeSlider_2.setInvertedControls(False)
        self.timeSlider_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.timeSlider_2.setObjectName("timeSlider_2")
        self.horizontalLayout_5.addWidget(self.timeSlider_2)
        self.totalTimeLabel_2 = QtWidgets.QLabel(self.layoutWidget)
        self.totalTimeLabel_2.setMinimumSize(QtCore.QSize(80, 0))
        self.totalTimeLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.totalTimeLabel_2.setObjectName("totalTimeLabel_2")
        self.horizontalLayout_5.addWidget(self.totalTimeLabel_2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(410, 560, 271, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/speaker-volume.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.volumeSlider_2 = QtWidgets.QSlider(self.layoutWidget_2)
        self.volumeSlider_2.setStyleSheet("background-color: rgb(78, 63, 96);\n"
"color: rgb(181, 144, 204);")
        self.volumeSlider_2.setMaximum(100)
        self.volumeSlider_2.setPageStep(0)
        self.volumeSlider_2.setProperty("value", 100)
        self.volumeSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider_2.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.volumeSlider_2.setTickInterval(1)
        self.volumeSlider_2.setObjectName("volumeSlider_2")
        self.horizontalLayout_7.addWidget(self.volumeSlider_2)
        self.previousButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.previousButton_3.setGeometry(QtCore.QRect(90, 560, 31, 31))
        self.previousButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(46, 32, 58);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(57, 46, 69);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(112, 0, 132);\n"
"}")
        self.previousButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/control-skip-180.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton_3.setIcon(icon)
        self.previousButton_3.setObjectName("previousButton_3")
        self.playButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.playButton_3.setGeometry(QtCore.QRect(130, 560, 31, 31))
        self.playButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(46, 32, 58);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(57, 46, 69);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(112, 0, 132);\n"
"}")
        self.playButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton_3.setIcon(icon1)
        self.playButton_3.setObjectName("playButton_3")
        self.pauseButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pauseButton_2.setGeometry(QtCore.QRect(170, 560, 31, 31))
        self.pauseButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(46, 32, 58);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(57, 46, 69);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(112, 0, 132);\n"
"}")
        self.pauseButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/control-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton_2.setIcon(icon2)
        self.pauseButton_2.setObjectName("pauseButton_2")
        self.stopButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton_3.setGeometry(QtCore.QRect(210, 560, 31, 31))
        self.stopButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(46, 32, 58);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(57, 46, 69);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(112, 0, 132);\n"
"}")
        self.stopButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/control-stop-square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton_3.setIcon(icon3)
        self.stopButton_3.setObjectName("stopButton_3")
        self.nextButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton_2.setGeometry(QtCore.QRect(250, 560, 31, 31))
        self.nextButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(46, 32, 58);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(57, 46, 69);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(112, 0, 132);\n"
"}")
        self.nextButton_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/control-skip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton_2.setIcon(icon4)
        self.nextButton_2.setObjectName("nextButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 520, 71, 71))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(46, 32, 58);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(57, 46, 69);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(112, 0, 132);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 10, 171, 51))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.currentTimeLabel.setText(_translate("MainWindow", "0:00"))
        self.totalTimeLabel_2.setText(_translate("MainWindow", "0:00"))
        self.label.setText(_translate("MainWindow", "Disida"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
